# Generated by Django 2.0.5 on 2018-05-22 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to=settings.AUTH_USER_MODEL),
        ),
    ]
