# Generated by Django 2.0.5 on 2018-05-22 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pizzarias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioPizzaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faturamento', models.DecimalField(decimal_places=2, max_digits=11)),
                ('maior_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pizzaria', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='relatorio', to='pizzarias.Pizzaria')),
            ],
        ),
    ]
