# Generated by Django 2.0.5 on 2018-05-22 02:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pizzarias', '0002_itemcardapio'),
        ('users', '0002_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('item_cardapio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizzarias.ItemCardapio')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data', models.DateTimeField()),
                ('endereco_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Endereco')),
            ],
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.Pedido'),
        ),
    ]
