# Generated by Django 2.0.5 on 2018-05-22 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('pedidos', '0001_initial'),
        ('pizzarias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='endereco_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='usuarios.Endereco'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pizzaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='pizzarias.Pizzaria'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='item_cardapio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizzarias.ItemCardapio'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.Pedido'),
        ),
    ]
