# Generated by Django 2.0.5 on 2018-05-22 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzarias', '0002_itemcardapio'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pizzaria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='pizzarias.Pizzaria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='endereco_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='users.Endereco'),
        ),
    ]
