# Generated by Django 2.0.5 on 2018-05-22 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzarias', '0002_auto_20180522_1636'),
        ('pedidos', '0002_auto_20180522_1610'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itempedido',
            unique_together={('pedido', 'item_cardapio')},
        ),
    ]
