# Generated by Django 2.0.5 on 2018-05-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tem_lactose', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='saborpizza',
            name='ingredientes',
            field=models.ManyToManyField(related_name='pizzas', to='pizzas.Ingrediente'),
        ),
    ]
