# Generated by Django 2.0.5 on 2018-05-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_auto_20180522_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaborPizzaMaterializedView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('tem_lactose', models.BooleanField()),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='saborpizza',
            name='tem_lactose_denormalized',
            field=models.BooleanField(default=True, editable=False),
            preserve_default=False,
        ),
    ]
