# Generated by Django 2.0.5 on 2018-05-22 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCardapio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pizzaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='itemcardapio',
            name='pizzaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_cardapio', to='pizzarias.Pizzaria'),
        ),
        migrations.AddField(
            model_name='itemcardapio',
            name='sabor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizzas.SaborPizza'),
        ),
    ]
