# Generated by Django 2.0.5 on 2018-05-22 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_auto_20180522_0105'),
        ('pizzarias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCardapio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pizzaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizzarias.Pizzaria')),
                ('sabor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizzas.SaborPizza')),
            ],
        ),
    ]
