# Generated by Django 2.0.5 on 2018-05-22 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
        ('pizzarias', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemcardapio',
            unique_together={('pizzaria', 'sabor')},
        ),
    ]
