# Generated by Django 2.0.5 on 2018-05-22 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzarias', '0002_itemcardapio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcardapio',
            name='pizzaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_cardapio', to='pizzarias.Pizzaria'),
        ),
    ]
