# Generated by Django 2.0.5 on 2018-05-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzarias', '0003_auto_20180522_2052'),
        ('pizzas', '0003_auto_20180523_2310'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewpizza',
            unique_together={('sabor', 'pizzaria')},
        ),
    ]
