# Generated by Django 2.0.5 on 2018-05-21 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
        ('pizzarias', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewpizza',
            unique_together={('sabor', 'pizzaria')},
        ),
    ]
